[project]
name = "del-academic-navigator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Petra Ignatius Pengayoman Naibaho", email = "petranaibaho5@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
del-academic-navigator = "del_academic_navigator:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
